"""fields bio and last_seen added to User Class

Revision ID: 3d26e791fe2e
Revises: fefc1c9e1fa1
Create Date: 2020-05-14 21:30:26.064461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d26e791fe2e'
down_revision = 'fefc1c9e1fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('app', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'last_seen')
    op.drop_column('app', 'bio')
    # ### end Alembic commands ###
